БСТ-1904 Якушев Кирилл, вариант 21

№1. Задание

In [2]:
print ("Hello, world!")

Hello, world!


№2. Задание

In [1]:
import numpy as np
import time
import random
try:
    m = int(input("Введите количество строк m"))
except ValueError:
    m = 50
try:
    n = int(input("Введите число столбцов n"))
except ValueError:
    n = 50
try:
    min_lim = int(input("Введите минимальное число min_lim"))
except ValueError:
    min_lim = -250
try:
    max_lim = int(input("Введите максимальное число max_lim"))
except ValueError:
    max_lim = 1021
A = np.empty((m, n))
for i in range(m):
    for j in range(n):
        A[i, j] = random.randint(min_lim, max_lim)
print("Ваш массив: ")
print(A)

Введите количество строк m 3
Введите число столбцов n 5
Введите минимальное число min_lim -1
Введите максимальное число max_lim 8


Ваш массив: 
[[ 5.  6.  0.  0.  7.]
 [ 2.  6.  5.  3.  8.]
 [ 8.  5.  1. -1.  7.]]


№3. Задание

Выбором

In [3]:
%%time
def SelectionSort(Arr):
    for i in range(len(Arr) - 1):
        m = i
        j = i + 1
        while j < len(Arr):
            m = j
            j = j + 1
            Arr[i], Arr[m] = Arr[m], Arr[i]


import numpy as np
B = np.empty(m*n)
C = np.empty((m, n))
z = 0
for x in range(m):
    for y in range(n):
        B[z] = A[x, y]
        z = z + 1
SelectionSort(B)
z = 0
for x in range(m):
    for y in range(n):
        C[x, y] = B[z]
        z = z + 1
print(C)

[[ 7. -1.  1.  5.  8.]
 [ 8.  3.  5.  6.  2.]
 [ 7.  0.  0.  6.  5.]]
Wall time: 0 ns


Вставкой

In [13]:
def insertion_sort(Arr):
    for i in range(1, len(Arr)):
        temp = Arr[i]
        j = i - 1
        while (j >= 0 and temp < Arr[j]):
            Arr[j + 1] = Arr[j]
            j = j - 1
        Arr[j + 1] = temp
 
 
import numpy as np
B = np.empty(m*n)
C = np.empty((m, n))
z = 0
for x in range(m):
    for y in range(n):
        B[z] = A[x, y]
        z = z + 1
SelectionSort(B)
z = 0
for x in range(m):
    for y in range(n):
        C[x, y] = B[z]
        z = z + 1
print(C)

[[ 1.  2.  4.  6. 11.]
 [16. 19. 20. 21. 27.]
 [30. 30. 35. 36. 37.]
 [37. 39. 39. 39. 41.]
 [42. 43. 47. 49. 50.]]


Обменом

In [14]:
%%time
def Bubble(A):
    for j in range(len(A) - 1, 0, -1):
        for i in range(0, j):
            if A[i] > A[i + 1]:
                A[i], A[i + 1] = A[i + 1], A[i]

import numpy as np
B = np.empty(m*n)
C = np.empty((m, n))
z = 0
for x in range(m):
    for y in range(n):
        B[z] = A[x, y]
        z = z + 1
Bubble(B)
z = 0
for x in range(m):
     for y in range(n):
        C[x, y] = B[z]
        z = z + 1
print(C)        

[[ 1.  2.  4.  6. 11.]
 [16. 19. 20. 21. 27.]
 [30. 30. 35. 36. 37.]
 [37. 39. 39. 39. 41.]
 [42. 43. 47. 49. 50.]]
Wall time: 1e+03 µs


Шелла

In [15]:
%%time
def shell(Arr):
    step = len(Arr) // 2
    while step:
        for i, el in enumerate(Arr):
            while i >= step and Arr[i - step] > el:
                Arr[i] = Arr[i - step]
                i -= step
            Arr[i] = el
        step = 1 if step == 2 else int(step * 5.0 / 11)
        
import numpy as np
B = np.empty(m*n)
C = np.empty((m, n))
z = 0
for x in range(m):
    for y in range(n):
        B[z] = A[x, y]
        z = z + 1
shell(B)
z = 0
for x in range(m):
    for y in range(n):
        C[x, y] = B[z]
        z = z + 1
print(C)

[[ 1.  2.  4.  6. 11.]
 [16. 19. 20. 21. 27.]
 [30. 30. 35. 36. 37.]
 [37. 39. 39. 39. 41.]
 [42. 43. 47. 49. 50.]]
Wall time: 999 µs


Пирамидальная сортировка

In [16]:
def heapsort(Arr):
    build_max_heap(Arr)
    for i in range(len(Arr) - 1, 0, -1):
        Arr[0], Arr[i] = Arr[i], Arr[0]
        max_heapify(Arr, index=0, size=i)
        
def parent(i):
    return (i - 1)//2
 
def left(i):
    return 2*i + 1
 
def right(i):
    return 2*i + 2
 
def build_max_heap(Arr):
    length = len(Arr)
    start = parent(length - 1)
    while start >= 0:
        max_heapify(Arr, index=start, size=length)
        start = start - 1
        
def max_heapify(Arr, index, size):
    l = left(index)
    r = right(index)
    if (l < size and Arr[l] > Arr[index]):
        largest = l
    else:
        largest = index
    if (r < size and Arr[r] > Arr[largest]):
        largest = r
    if (largest != index):
        Arr[largest], Arr[index] = Arr[index], Arr[largest]
        max_heapify(Arr, largest, size)
 
 
import numpy as np
B = np.empty(m*n)
C = np.empty((m, n))
z = 0
for x in range(m):
    for y in range(n):
        B[z] = A[x, y]
        z = z + 1
heapsort(B)
z = 0
for x in range(m):
    for y in range(n):
        C[x, y] = B[z]
        z = z + 1
print(C)

[[ 1.  2.  4.  6. 11.]
 [16. 19. 20. 21. 27.]
 [30. 30. 35. 36. 37.]
 [37. 39. 39. 39. 41.]
 [42. 43. 47. 49. 50.]]


Быстрая сортировка

In [17]:
def quick(Arr, start, end):
    if end - start > 1:
        p = partition(Arr, start, end)
        quick(Arr, start, p)
        quick(Arr, p + 1, end)
 
 
def partition(Arr, start, end):
    pivot = Arr[start]
    i = start + 1
    j = end - 1
 
    while True:
        while (i <= j and Arr[i] <= pivot):
            i = i + 1
        while (i <= j and Arr[j] >= pivot):
            j = j - 1
 
        if i <= j:
            Arr[i], Arr[j] = Arr[j], Arr[i]
        else:
            Arr[start], Arr[j] = Arr[j], Arr[start]
            return j
 
 
import numpy as np
B = np.empty(m*n)
C = np.empty((m, n))
z = 0
for x in range(m):
    for y in range(n):
        B[z] = A[x, y]
        z = z + 1        
quick(B, 0, len(A))
z = 0
for x in range(m):
    for y in range(n):
        C[x, y] = B[z]
        z = z + 1
print(C)

[[ 1. 11. 16. 30. 42.]
 [50. 37. 27. 49.  6.]
 [37. 19. 20. 43. 30.]
 [35.  4. 39. 36. 21.]
 [41. 47. 39.  2. 39.]]


In [ ]:
Турнирная сортировка

In [8]:
def TournamentSort(array):
    Arr= array.copy()
    for i in range(len(Arr)):
        tournamentSort(Arr[i])
    return Arr
def tournamentSort(Arr):
    tree = [None] * 2 * (len(Arr) + len(Arr) % 2)
    index = len(tree) - len(Arr) - len(Arr) % 2
    
    for i, v in enumerate(Arr):
        tree[index + i] = (i, v)
    
    for j in range(len(Arr)):
        n = len(Arr)
        index = len(tree) - len(Arr) - len(Arr) % 2
        while index > -1:
            n = (n + 1) // 2
            for i in range(n):
                i = max(index + i * 2, 1) 
                if tree[i] != None and tree[i + 1] != None:
                    if tree[i][1] < tree[i + 1][1]:
                        tree[i // 2] = tree[i]
                    else:
                        tree[i // 2] = tree[i + 1]
                else:
                    tree[i // 2] = tree[i] if tree[i] != None else tree[i + 1]
            index -= n

        index, x = tree[0]
        Arr[j] = x
        tree[len(tree) - len(Arr) - len(Arr) % 2 + index] = None
        
Arr = input().split()
Arr = [int(x) for x in Arr]
tournamentSort(Arr)
print(Arr)

 8 9 4 6 5


[4, 5, 6, 8, 9]


Задача №1

In [8]:
import time
import random

def checkFun(a, b, c):
    if a + b > c and a + c > b and b + c > 2:
        return 1
    else:
        return 0
def perimeter(a, b, c):
    return a + b + c

import numpy as np
N = int(input("Введите длину массива от 3 до 10000"))
if N < 3 or N > 10000:
    print("Число должно быть от 3 до 10000")
    N = int(input("Введите длину массива от 3 до 10000"))
A = np.empty(N)
for i in range(N):
        A[i] = random.randint(1, 10)
print(A)
perimeter_max = 0
for i in range(N - 2):
    for j in range(i + 1, N - 1):
        for z in range(j + 1, N):
            if checkFun(A[i], A[j], A[z]) == 1:
                if perimeter(A[i], A[j], A[z]) > perimeter_max:
                    perimeter_max = perimeter(A[i], A[j], A[z])
print("Максимально возможный периметр равен: " + str(perimeter_max))               

Введите длину массива от 3 до 100005
[4. 2. 2. 1. 7.]
Максимально возможный периметр равен: 8.0


Задача №3

In [23]:
import time
import random
def Bubble(A):
    for j in range(len(A) - 1, 0, -1):
        for i in range (0, j):
            if A[i] > A[i + 1]:
                A[i], A[i + 1] = A[i + 1], A[i]

import numpy as np
m = int(input("Введите количество строк m"))
if m < 2 or m > 100:
    print("Число должно быть от 2 до 100")
n = int(input("Введите число столбцов n"))
if n < 2 or n > 100:
    print("Число должно быть от 2 до 100")
A = np.empty((m, n))
for i in range(m):
    for j in range(n):
        A[i, j] = random.randint(1, 20)
print(A)
print(" ")
B = np.empty(n)
for i in range(-(m-2), 1):
    np.resize(B, len(np.diag(A, k = i)))
    B = np.diagonal(A, offset = i).copy()
    Bubble(B)
    np.fill_diagonal(A[-i:], B)
print(A)

Введите количество строк m4
Введите число столбцов n5
[[ 5. 15.  9.  8.  9.]
 [19. 19.  1. 17. 13.]
 [13. 20. 18. 15. 13.]
 [15. 15. 17. 13. 13.]]
 
[[ 5. 15.  9.  8.  9.]
 [17. 13.  1. 17. 13.]
 [13. 19. 18. 15. 13.]
 [15. 15. 20. 19. 13.]]
