# Задача №1. «Треугольник с максимальным периметром»

Массив A состоит из целых положительных чисел - длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно составить треугольник с положительной площадью - функция возвращает 0.

In [1]:
def maxPerimetr(arr):
    arr = sorted(arr, reverse=True)
    n = len(arr)
    for i in range(n - 2):
        if arr[i] < arr[i + 1] + arr[i + 2]:
            return arr[i] + arr[i + 1] + arr[i + 2]
    return 0

arr = [1, 2, 2]
print(arr,"-->", maxPerimetr(arr))
arr = [1, 2, 1]
print(arr,"-->", maxPerimetr(arr))
arr = [3, 2, 3, 4]
print(arr,"-->", maxPerimetr(arr))
arr = [3, 6, 2, 3]
print(arr,"-->", maxPerimetr(arr))

[1, 2, 2] --> 5
[1, 2, 1] --> 0
[3, 2, 3, 4] --> 10
[3, 6, 2, 3] --> 8


# Задача №2 «Максимальное число»

Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы вместе они образовали максимально возможное число.
Замечание: Результат может быть очень большим числом, поэтому представьте его как string, а не integer.

In [2]:
def maxNum(nums):
    nums.sort(key=lambda n: n % 10)
    
    res = ''.join(str(e) for e in nums)
    return res

print("[10, 2] -->", maxNum([10, 2]))
print("[3, 30, 34, 5, 9] -->", maxNum([3, 30, 34, 5, 9]))
print("[1] -->", maxNum([1]))
print("[10] -->", maxNum([10]))

[10, 2] --> 102
[3, 30, 34, 5, 9] --> 3033459
[1] --> 1
[10] --> 10


# Задача №3 

Дана строка s, вернуть самую длинную полиндромную подстроку в s.

In [4]:
def Palindromes(s):
    s_rev = s[::-1]
    return s_rev == s
def LongestPalidrome(s):
    max_len = 1
    max_pal = s[0]
    for i in range(len(s) - 1):
        for j in range (i + 1, len(s)):
            if Palindromes(s[i:j]) and len(s[i:j]) > max_len:
                max_len = len(s[i:j])
                max_pal = s[i:j]
    return max_pal

s = "abb2x2xr"
print(LongestPalidrome(s))

2x2


# Задача №4

Дана матрица mat размером m * n, значения - целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу.

In [4]:
import time
import random
import numpy as np
def BubbleSort(A):
    for j in range(len(A) - 1, 0, -1):
        for i in range(0, j):
            if A[i] > A[i + 1]:
                A[i], A[i + 1] = A[i + 1], A[i]                

m = int(input("Введите количество строк"))
if m < 1 or m > 100:
    print("Число должно быть от 1 до 100")
    m = int(input("Введите количество строк"))
n = int(input("Введите количество столбцов"))
if n < 1 or n > 100:
    print("Число должно быть от 1 до 100")
    n = int(input("Введите количество столбцов"))
A = np.empty((m, n))
for i in range(m):
    for j in range(n):
        A[i, j] = random.randint(1, 100)
print(A)
print(" ")
B = np.empty(n)
for i in range(-(m - 2), 1):
    np.resize(B, len(np.diag(A, k = i)))
    B = np.diagonal(A, offset = i).copy()
    BubbleSort(B)
    np.fill_diagonal(A[-i:], B)
for i in range(1, n):
    np.resize(B, len(np.diag(A, k = i)))
    B = np.diagonal(A, offset = i).copy()
    BubbleSort(B)
    np.fill_diagonal(A[:,i:], B)
print(A)

Введите количество строк5
Введите количество столбцов5
[[42. 33. 24. 84.  7.]
 [66. 81. 39. 57. 63.]
 [77. 56. 44. 85. 41.]
 [14. 13. 96. 72. 49.]
 [94. 95. 29. 21. 28.]]
 
[[28. 33. 24. 63.  7.]
 [21. 42. 39. 41. 84.]
 [13. 56. 44. 49. 57.]
 [14. 29. 66. 72. 85.]
 [94. 95. 77. 96. 81.]]


# Задача №5

Вернуть количество отдельных непустых подстрок текста, которые могут быть записаны как конкатенация некоторой строки с самой собой
(т.е. онаможет быть записана, как a + a, где a - некоторая строка).

In [4]:
def Conc(s):
    s_arr = []
    for i in range(len(s) - 1):
        for j in range(i + 1, len(s)):
            if s.startswith(s[i:j], j) and not s[i: j] in s_arr:
                s_arr.append(s[i:j])
    return len(s_arr)

s = "abcabcabc"
print(Conc(s))

3


# Задача №6

На столе стоят 3n стопок монет.
Вы и ваши друзья Алиса и Боб забираете стопки монет последующему алгоритму:

Вы выбираете 3 стопки монет из оставшихся на столе.
Алиса забирает себе стопку с максимальным количеством монет.
Вы забираете одну из двух оставшихся стопок.
Боб забирает последнюю стопку.
Если еще остались стопки, то действия повторяются с первого шага.
Дан массив целых положительных чисел piles. Напишите функцию, возвращающую максимальное число монет, которое вы можете получить

In [3]:
def game(piles):
    piles.sort()
    result = 0
    begin = len(piles) // 3
    for i in range(begin, len(piles), 2):
        result = result + piles[i]
    return result

piles = [2,4,1,2,7,8]
print(game(piles))

9


# Задача №7

Даны две строки: s1 и s2 с одинаковым размером, проверьте,
может ли некоторая перестановка строки s1 “победить” некоторую перестановку строки s2 или наоборот.

Строка x может “победить” строку y (обе имеют размер n), если x[i]> = y [i] (в алфавитном порядке) для всех i от 0 до n-1.

In [5]:
def stringWin(s1, s2):
    str1 = sorted(s1)
    str2 = sorted(s2)
    f1 = True
    f2 = True
    
    for i in range(len(str1)):
        if str1[i] < str2[i]:
            f1 = False
        if str1[i] > str2[i]:
            f2 = False
    return(f1 or f2)
    
a1 = 'abc'
a2 = 'xya'
print(stringWin(a1, a2))

a1 = 'abe' 
a2 = 'acd'
print(stringWin(a1, a2))

True
False


# Задача №8 

Дан массив отрезков intervals, в котором intervals[i] = [starti, endi], некоторые отрезки могут пересекаться.
Напишите функцию, которая объединяет все пересекающиеся отрезки в один и возвращает новый массив непересекающихся отрезко

In [6]:
def merge(intervals):
    intervals.sort(key=lambda x: x[0])
    
    result = []
    for interval in intervals:
        if not result or result[-1][1] < interval[0]:
            result.append(interval)
        else:
            result[-1][1] = max(result[-1][1], interval[1])
    return(result)
    
intervals = [[1, 3], [2, 7], [8, 10], [15, 18]]
print(intervals, ' --> ', merge(intervals))
intervals = [[1,4],[4,5]]
print(intervals, ' --> ', merge(intervals))

[[1, 7], [2, 7], [8, 10], [15, 18]]  -->  [[1, 7], [8, 10], [15, 18]]
[[1, 5], [4, 5]]  -->  [[1, 5]]


# Задача №9

Некоторые сферические шарики распределены по двухмерному пространству. Для каждого шарика даны x координаты начала и конца его горизонтального диаметра. Так как пространство двумерно, то y координаты не имеют значения в данной задаче. Координата x_start всегда меньше x_end.

Стрелу можно выстрелить строго вертикально (вдоль y оси) из разных точек xоси. Шарик с координатами x_start и x_end уничтожается стрелой, если она была выпущена из такой позиции x, что xstart ⩽ x ⩽ xend.
Когда стрела выпущена, она летит в пространстве бесконечное время (уничтожая все шарики на пути).

Дан массив points, где points[i] = [xstart, xend]. Напишите функцию, возвращающую минимальное количество стрел, которые нужно выпустить, чтобы уничтожить все шарики.

In [7]:
def balloons(arr):
    arr = sorted(arr)
    result = 1
    prev = arr[0]
    
    for balloon in arr:
        if prev[1] < balloon[0]:
            prev = balloon
            result += 1
        else:
            prev[1] = min(balloon[1], prev[1])
    return(result)

points = [[10,16],[2,8],[1,6],[7,12]]
print(points, '-->', balloons(points))
points = [[1,2],[3,4],[5,6],[7,8]]
print(points, '-->', balloons(points))
points = [[1,2],[2,3],[3,4],[4,5]]
print(points, '-->', balloons(points))
points = [[1,2]]
print(points, '-->', balloons(points))
points = [[2,3],[2,3]]
print(points, '-->', balloons(points))

[[10, 16], [2, 8], [1, 6], [7, 12]] --> 2
[[1, 2], [3, 4], [5, 6], [7, 8]] --> 4
[[1, 2], [2, 3], [3, 4], [4, 5]] --> 2
[[1, 2]] --> 1
[[2, 3], [2, 3]] --> 1
